version: "2"

services:
  app:
    build: ./
    restart: always
    ports:
      - "80:80" # web
      - "22:22" # ssh
    volumes:
      - ./../:/apps # all apps
      - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
    links:
      - mariadb
      - mongodb

  mariadb:
    image: tutum/mariadb
    restart: always
    ports:
      - "33060:3306"
    environment:
      MARIADB_USER: admin # cannot be changed ( for info. only )
      MARIADB_PASS: secret
    volumes:
      - ./mariadb:/var/lib/mysql # database files
  mongodb:
    image: mongo
    restart: on-failure
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    tty: true
